#AUTOGENERATED! DO NOT EDIT! File to edit: dev/21_classification_losses.ipynb (unless otherwise specified).

__all__ = ['hemorrhage_bce']

#Cell
from fastai.vision import *

#Cell
def hemorrhage_bce(input, target):
    w = tensor(2,1,1,1,1,1).to(input.device)
    return F.binary_cross_entropy_with_logits(input, target, w)