#AUTOGENERATED! DO NOT EDIT! File to edit: dev/00_segmentation_data_prep.ipynb (unless otherwise specified).

__all__ = ['dummy_func']

#Cell
from fastai.vision import *

#Cell
print("Testing notebook2script")

#Cell
def dummy_func(x): pass