#AUTOGENERATED! DO NOT EDIT! File to edit: dev/00_testing_notebook_export.ipynb (unless otherwise specified).

__all__ = ['dummy_func']

#Cell
from fastai.vision import *

#Cell
print("Testing notebook/")

#Cell
def dummy_func(x): pass