#AUTOGENERATED! DO NOT EDIT! File to edit: dev/11_segmentation_losses_mulitlabel.ipynb (unless otherwise specified).

__all__ = ['lovasz_softmax', 'cross_entropy']

#Cell
from fastai.vision import *
from .lovasz_loss import *

#Cell
cross_entropy = CrossEntropyFlat(axis=1)