#AUTOGENERATED! DO NOT EDIT! File to edit: dev/11_segmentation_losses.ipynb (unless otherwise specified).

__all__ = ['lovasz_hinge', 'lovasz_softmax', 'cross_entropy', 'dice_loss']

#Cell
from fastai.vision import *
from .lovasz_loss import *

#Cell
cross_entropy = CrossEntropyFlat(axis=1)

#Cell
def dice_loss(input, target):
    "input: logits (B,2,H,W), target: labels (B,1,H,W)"
    smooth = 1.
    input = input.softmax(1)[:,1,:].unsqueeze(1).contiguous()
    iflat = input.view(-1)
    tflat = target.view(-1).float()
    intersection = (iflat * tflat).sum()
    return 1 - ((2. * intersection + smooth) / (iflat.sum() + tflat.sum() + smooth))