#AUTOGENERATED! DO NOT EDIT! File to edit: dev/11_segmentation_losses.ipynb (unless otherwise specified).

__all__ = ['lovasz_hinge', 'lovasz_softmax', 'dice_loss']

#Cell
from fastai.vision import *
from .lovasz_loss import *

#Cell
def dice_loss(input, target):
    "binary dice loss"
    smooth = 1.
    iflat = input.view(-1)
    tflat = target.view(-1)
    intersection = (iflat * tflat).sum()
    return 1 - ((2. * intersection + smooth) / (iflat.sum() + tflat.sum() + smooth))