#AUTOGENERATED! DO NOT EDIT! File to edit: dev/11_segmentation_losses_mulitlabel.ipynb (unless otherwise specified).

__all__ = ['lovasz_softmax', 'cross_entropy', 'bce_sigmoid']

#Cell
from fastai.vision import *
from .lovasz_loss import *

#Cell
cross_entropy = CrossEntropyFlat(axis=1)

#Cell
def bce_sigmoid(input, target, **bce_kwargs):
    "Background is not predict, e.g. codes.txt and background value in label image is 0"
    nclasses = input.size(1)
    trange = tensor(np.arange(1, nclasses+1))[None,...,None,None].to(target.device)
    new_target = target == trange
    return F.binary_cross_entropy_with_logits(input, new_target.float(), **bce_kwargs)